### ISSUE TITLE
Property:higherClassification

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/tcs2#230]
### higherClassification (property)

Associated literal term: http://rs.tdwg.org/dwc/terms/higherClassification

|    |    |
|----|----|
| Label | Higher classification|
| Definition | List or array of Taxon Concepts that starts with the highest-ranked Taxon Concept in a classification (generally a Kingdom or Domain) and end with the 'parent'. |
| Usage notes |  |
| Comments | Higher classification is often used in breadcrumb trails. `tcs:higherClassification` is the IRI equivalent of `dwc:higherClassification`. |
| Required | No |
| Repeatable | No |
| Constraints | [Object] |

#### Mapping

|    |    |
|----|----|
| Darwin Core | http://rs.tdwg.org/dwc/terms/higherClassification |

**Comment by nielsklazenga** [comment]
Remove from v. 2.0.0:

```yaml
# property: higherClassification
- localName: higherClassification
  label: Higher classification
  definition: >-
    List or array of Taxon Concepts that starts with the highest-ranked Taxon
    Concept in a classification (generally a Kingdom or Domain) and ends with
    the parent.
  usage: >-
    `higherClassification` is a list or array of Taxon Concepts.
  notes: >-
    `higherClassification` is the IRI equivalent of `dwc:higherClassification`. 
  examples:
    - TaxonConcept-higherClassification-1
  organizedInClass: http://rs.tdwg.org/tcs/terms/TaxonConcept
  repeatable: No
  required: No
  type: http://www.w3.org/1999/02/22-rdf-syntax-ns#Property
  github: 230
```

```turtle
@prefix tcs: <http://rs.tdwg.org/tcs/terms/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix dwc: <http://rs.tdwg.org/dwc/terms/> .

<https://www.catalogueoflife.org/data/taxon/4WSQK> a tcs:TaxonConcept ;
    dcterms:title "Sequioadendron giganteum sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Sequoiadendron giganteum (Lindl.) J.T. Buchholz" ;
    tcs:higherClassification <https://www.catalogueoflife.org/data/taxon/P> ,
            <https://www.catalogueoflife.org/data/taxon/TP> ,
            <https://www.catalogueoflife.org/data/taxon/GG> ,
            <https://www.catalogueoflife.org/data/taxon/623FD> ,
            <https://www.catalogueoflife.org/data/taxon/8SY> ,
            <https://www.catalogueoflife.org/data/taxon/7FQF> .

<https://www.catalogueoflife.org/data/taxon/P> a tcs:TaxonConcept ;
    dcterms:title "Plantae sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Plantae" .

<https://www.catalogueoflife.org/data/taxon/TP> a tcs:TaxonConcept ;
    dcterms:title "Tracheophyta sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Tracheophyta" .

<https://www.catalogueoflife.org/data/taxon/GG> a tcs:TaxonConcept ;
    dcterms:title "Pinopsida sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Pinopsida" .

<https://www.catalogueoflife.org/data/taxon/623FD> a tcs:TaxonConcept ;
    dcterms:title "Pinales sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Pinales" .

<https://www.catalogueoflife.org/data/taxon/8SY> a tcs:TaxonConcept ;
    dcterms:title "Cupressaceae sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Cupressaceae" .

<https://www.catalogueoflife.org/data/taxon/7FQF> a tcs:TaxonConcept ;
    dcterms:title "Sequioadendron sec. Catalogue of Life 2024-01-24"
    tcs:accordingTo <https://doi.org/10.48580/dfrdl> ;
    dwc:scientificName "Sequoiadendron" .
```
